# Name of the workflow
name: Generate Release Notes

#  Run on every commit tag which begins with 'v' (e.g. v1.2.0)
on:
  push:
    tags:
      - 'v*.*.*'

# Automatically create a Github Release, with release details specifies (the relevent commits)

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Release Notes
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
